### ISSUE TITLE
Support for both fluent and conventional getters/setters

### ISSUE THREAD

**Issue by soberich** [mapstruct/mapstruct-idea#23]
Support for 
```java
@Data
@Accessors(fluent-true)
class A {}
```
with both
```java
new A().a().b().c()
new A().a("").b("").c("")
//and
new A().getA().getB().getC()
new A().setA().setB().setC()
```

**Comment by filiphr** [comment]
Thanks for the issue @soberich. Support for fluent setters has been added on master and would be part of the next release.

Support for fluent getters is unfortunately not possible due to technical issues during compilation. A fluent getter (a getter that does not start with `get` or `is`) is basically every method of a class, so there is really no way for us to know if a certain method is a fluent getter or a normal method. Fluent setters are easier because you can make the assumption that a fluent setter always returns the parent type of the method.

**Comment by soberich** [comment]
Magic! You're awesome guys. Feel free to close.
