### ISSUE TITLE
Redundant default parameter value assignment warning shouldn't appear if target is a string

### ISSUE THREAD

**Issue by dragove** [mapstruct/mapstruct-idea#93]
In this case
```java
class A {
  String name;
}

@Mapping(target="name", defaultValue="")
A cloneA(A s);
```
the string after defaultValue shows redundant warning. In this case, it stands for empty string if `s.name` is null.

**Comment by filiphr** [comment]
This is a tricky one. We need to investigate if we can override the IntelliJ redundant warning, because for MapStruct there is a difference.

**Comment by filiphr** [comment]
Since IntelliJ 2021.2 there is an extension point called `DefaultAnnotationParamInspection.IgnoreAnnotationParamSupport`, which allows us to instruct IntelliJ to ignore the "Redundant default parameter assignment" warning. We are going to bump our minimum supported IntelliJ to 2021.2 in order to use the new extension point.
